services:
  app:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    profiles:
      - app
      - all
    volumes:
      - .:/workspace/gargoyle
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      PREFIX: ','
      MONGO_URI: ${MONGO_URI}
      DEBUG_LEVEL: 6
      LOG_TO_FILE: false
    networks:
      - gargoyle

  mongo:
    hostname: mongo
    image: mongo:latest
    expose: [27017]
    profiles:
      - aux
      - all
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DBUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DBPASSWORD}
    volumes:
      - ./container/db:/data/db
      - ./container/configdb:/data/configdb
    networks:
      - gargoyle

  detoxify-api:
    hostname: detoxify-api
    profiles:
      - aux
      - all
    volumes:
      - ./container/.cache/application:/root/.cache
      - ./container/.cache/packages:/.cached_packages
    expose: [8000]
    image: ghcr.io/ceraia/detoxify-api:latest
    networks:
      - gargoyle

  ollama:
    hostname: ollama
    profiles:
      - aux
      - all
    volumes:
      - ./container/ollama:/root/.ollama
    expose: [11434]
    image: ollama/ollama
    networks:
      - gargoyle

networks:
  gargoyle:
    driver: bridge
