services:
  app:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - .:/workspace/gargoyle
    depends_on:
      - mongo
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      MONGO_URI: mongodb://${DBUSERNAME}:${DBPASSWORD}@mongo:27017/gargoyle?authSource=admin
      DEBUG: true
    labels:
      traefik.enable: 'false'
    networks:
      - gargoyle

  mongo:
    hostname: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DBUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DBPASSWORD}
    volumes:
      - ./container/db:/data/db
      - ./container/configdb:/data/configdb
    networks:
      - gargoyle

  detoxify-api:
    profiles: 
      - ai
    hostname: detoxify-api
    volumes:
      - ./container/.cache/application:/root/.cache
      - ./container/.cache/packages:/.cached_packages
    expose: [8000]
    image: ghcr.io/ceraia/detoxify-api:latest
    networks:
      - gargoyle

networks:
  gargoyle:
    driver: bridge
