services:
  mongo:
    profiles:
      - db
      - ai
    hostname: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DBUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DBPASSWORD}
    volumes:
      - ./container/db:/data/db
    networks:
      - gargoyle
    ports:
      - 27017:27017

  express:
    profiles:
      - db
      - ai
    image: mongo-express:latest
    ports:
      - 80:80
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_PASSWORD: ${DBPASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${DBUSERNAME}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DBUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DBPASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DBUSERNAME}:${DBPASSWORD}@mongo:27017/gargoyle?authSource=admin
    networks:
      - gargoyle
  
  ollama:
    profiles:
      - ai
    hostname: ollama
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    restart: unless-stopped
    volumes:
      - ai:/model_files
    networks:
      - gargoyle
  
  chat-webui:
    profiles:
      - ai
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 3000:8080
    restart: unless-stopped
    depends_on:
      - ollama
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    volumes:
      - ./container/openwebui:/app/backend/data
    networks:
      - gargoyle

networks:
  gargoyle:
    driver: bridge

volumes:
  ai: