services:
  mongo:
    profiles:
      - db
      - ai
    hostname: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DBUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DBPASSWORD}
    volumes:
      - ./container/db:/data/db
    networks:
      - gargoyle
    ports:
      - 27017:27017

  detoxify-api:
    profiles: 
      - ai
    hostname: detoxify-api
    volumes:
      - ./container/.cache/application:/root/.cache
      - ./container/.cache/packages:/.cached_packages
    expose: [8000]
    image: ghcr.io/ceraia/detoxify-api:latest
    networks:
      - gargoyle

networks:
  gargoyle:
    driver: bridge