services:
  mongo:
    profiles:
      - db
    hostname: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DBUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DBPASSWORD}
    volumes:
      - ./container/db:/data/db
    networks:
      - gargoyle
    ports:
      - 27017:27017

  express:
    profiles:
      - db
    image: mongo-express:latest
    ports:
      - 80:80
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_PASSWORD: ${DBPASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${DBUSERNAME}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DBUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DBPASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DBUSERNAME}:${DBPASSWORD}@mongo:27017/gargoyle?authSource=admin
    networks:
      - gargoyle

networks:
  gargoyle:
    driver: bridge

volumes:
  ai: