version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - .:/workspace/gargoyle
    depends_on:
      - mongo
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      MONGO_URI: mongodb://${CERAIA_MONGODB_USERNAME}:${CERAIA_MONGODB_PASSWORD}@mongo:27017/gargoyle?authSource=admin
      STATUS_CHANNEL: ${CERAIA_BOT_STATUS_CHANNEL}
      DEBUG: true
    labels:
      traefik.enable: "false"
    networks:
      - gargoyle

  mongo:
    hostname: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CERAIA_MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${CERAIA_MONGODB_PASSWORD}
    volumes:
      - ./.container/mongo-db:/app/backend/data
      - ./.container/mongo-configdb:/app/backend/data
    networks:
      - gargoyle

  express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_PASSWORD: ${CERAIA_MONGODB_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${CERAIA_MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${CERAIA_MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${CERAIA_MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${CERAIA_MONGODB_USERNAME}:${CERAIA_MONGODB_PASSWORD}@mongo:27017/
    networks:
      - gargoyle

networks:
  gargoyle:
    driver: bridge
